### ISSUE TITLE
Make file not caching all files

### ISSUE THREAD

**Issue by ladsong** [CESARBR/knot-thing-source#3]
The files: knot_types.h,  knot_protocol.h, and knot_protocol.c are not being inserted into the .zip file when the makefile is used. The files are in the download folder.

**Comment by lhcavalcanti** [comment]
Hello Ladson,
I also tried the makefile 2 weeks ago, and it doesn't catch all files. 
Unfortunately I tried it again (in the same conditions) and worked, I talked with some members on the project and they told that it already happened with them, and they are already investigating it.

1. If it happens, you can manually add this files on the `/src` folder, inside the library folder (it is on `home/Arduino/libraries`).
2. Remember when running the make, pass as argument of the release you and like:
`make release=KNOT-v01.02-rc11`

**Comment by rodrigoalves1** [comment]
Hey everyone, 
could you please provide more details about when this happened? your OS for example and the output of the make on your terminal.

I try to always run` make clean` before building. Please be aware, passing the `release` argument on your make command, as in `make release=tag `(or master, but always compatible with the tag you are using on your gateway), will also download the knot-thing-source code from github and any local changes on the lib won't have effect.

In the case this continues to happen you can, as lhcavalcanti said, copy the files manually.

**Comment by jcorde** [comment]
Outdated bug. Fixed!
